{
 "title": "Redirects API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Path requests",
   "type": "table",
   "description": "HTTP requests by path",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "http_requests_total_by_path{instance=\"localhost:8082\", path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Active HTTP requests",
   "type": "stat",
   "description": "Active HTTP requests getting processed by API",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_active_requests{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Total HTTP requests processed by API",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status ",
   "type": "table",
   "description": "HTTP Status counter",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "http_response_status{instance=\"localhost:8082\", status!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Go Routines",
   "type": "stat",
   "description": "Go routines currently being used by API",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Heap storage",
   "type": "stat",
   "description": "Heap Storage used by GC for the current Go process",
   "gridPos": { "h": 4, "w": 7, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total - go_memstats_free_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Heap memory usage",
   "type": "stat",
   "description": "Memory used by GC for the current Go process",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_bytes_free{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_bytes_released{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_bytes_unused{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Memory used by running go process",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}