name: CLI Release Workflow

on:
  push:
    # branches:
    #   - main
    tags:
      - '**-cli'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Specify the Go version

    - name: Building CLI Binary
      run: |
        cd cli/
        go mod tidy
        go build -o redirector .

    - name: Archive binary
      run: tar -czvf redirector.tar.gz cli/redirector

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        upload-artifact: redirector.tar.gz
        tag: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

