name: CLI Release Workflow

on:
  push:
    # branches:
    #   - main
    tags:
      - '**-cli'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Specify the Go version

    - name: Building and Archive CLI Binary
      run: |
        cd cli/
        go mod tidy
        go build -o redirector .
        tar -czvf redirector.tar.gz redirector 

    - name: Create Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
          cd cli/
          gh release create ${GITHUB_REF##*/} redirector.tar.gz

