name: Release Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Specify the Go version

    - name: Checking GitHub Container Registry Log in
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Container Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Container Image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}:latest

    - name: Building CLI Binary
      run: |
        cd cli/
        go mod tidy
        go build -o url-redirect-cli .

    - name: Archive binary
      run: tar -czvf url-redirect-cli.tar.gz cli/url-redirect-cli

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        upload-artifact: url-redirect-cli.tar.gz
        tag: 'latest' #${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

